# permissions for end users to edit bamelautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bamel-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: bamelautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.bamel.io
  resources:
  - bamelautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.bamel.io
  resources:
  - bamelautoscalers/status
  verbs:
  - get
